# Generated by Django 5.0.4 on 2024-04-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_options_room_partcipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='partcipants',
            new_name='participants',
        ),
    ]
